# Generated by Django 2.2.24 on 2023-03-03 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_auto_20230303_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Текст жалобы:')),
                ('flat', models.ForeignKey(null=True, on_delete='Квартира, на которую пожаловались:', to='property.Flat')),
                ('user', models.ForeignKey(null=True, on_delete='Кто жаловался:', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
