# Generated by Django 4.1.7 on 2023-03-04 22:10

from django.db import migrations
import phonenumbers


def normalize_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.filter(owners_phonenumber='+70000000000'):
        parsed_phonenumber = phonenumbers.parse(flat.owners_phonenumber, "RU")
        flat.owners_normalized_phonenumber = phonenumbers.format_number(
                parsed_phonenumber,
                phonenumbers.PhoneNumberFormat.E164)
        flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owners_normalized_phonenumber = None
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0005_flat_liked_by_flat_owners_normalized_phonenumber_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_phonenumbers, move_backward)
    ]
