# Generated by Django 4.1.7 on 2023-03-06 18:33

from django.db import migrations


def copy_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owners_pure_phone,
        )


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_rename_owners_normalized_phonenumber_flat_owners_pure_phone_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_flats_to_owners, move_backward)
    ]
