# Generated by Django 4.1.7 on 2023-03-09 19:05

from django.db import migrations


def connect_apartments_with_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all().iterator():
        flats = Flat.objects.filter(owner=owner.name, owners_pure_phone=owner.pure_phone)
        if flats:
            owner.flats.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20230306_2133'),
    ]

    operations = [
        migrations.RunPython(connect_apartments_with_owners)
    ]
