# Generated by Django 4.1.7 on 2023-03-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_remove_flat_owner_remove_flat_owners_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(db_index=True, null=True),
        ),
    ]
